name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Render DockerFile template
      run: |
        sh ./render.sh
      env:
        COMMIT_HASH: ${GITHUB_SHA::8}
        BRANCH: ${GITHUB_REF#refs/heads/}
        REPOSITORY_NAME: ${GITHUB_REPOSITORY#*/}

    - name: set global env
      id: global_env
      run: |
        echo "::set-output name=REPOSITORY_NAME::${GITHUB_REPOSITORY#*/}"
        echo "::set-output name=DOCKERHUB_IMAGE_NAME::gb64/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY#*/}"

    - name: Build the Docker image
      run: docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
